global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'python_server'
    static_configs:
      - targets: [ 'python_server:8000' ]

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]  # Адрес самого Prometheus

