# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.database import db


class Figure(db.Model):
    """NOTE: This class is auto generated by
     the swagger code generator program.

    Do not edit the class manually.
    """
    __tablename__ = 'figure'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    brand = db.Column(db.String(100), nullable=False)
    release = db.Column(db.Integer, nullable=False)
    scale = db.Column(db.String(10), nullable=False)
    size = db.Column(db.String(50), nullable=True)

    def __init__(self, id: int = None, name: str = None, brand: str = None, release: int = None, scale: str = None, size: str = None):
        self.id = id
        self.name = name
        self.brand = brand
        self.release = release
        self.scale = scale
        self.size = size

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Figure of this Figure.  # noqa: E501
        :rtype: Figure
        """
        return cls(
            id=dikt.get('id'),
            name=dikt.get('name'),
            brand=dikt.get('brand'),
            release=dikt.get('release'),
            scale=dikt.get('scale'),
            size=dikt.get('size')
        )

    def to_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'brand': self.brand,
            'release': self.release,
            'scale': self.scale,
            'size': self.size
        }
